name: eparens
description: Lisp, but not as we know it.
version: 0.1.0

environment:
  sdk: ">=2.0.0"

executables:
  eparens-osc:
  eparens-irc:
  eparens-repl:

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
